package com.example.tubemindai;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.tubemindai.adapters.ChatAdapter;
import com.example.tubemindai.models.ChatModel;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.textfield.TextInputEditText;

import java.util.ArrayList;
import java.util.List;

/**
 * Chat Activity - Chat interface for asking questions about the video
 */
public class ChatActivity extends AppCompatActivity {
    private MaterialToolbar toolbar;
    private RecyclerView rvChatMessages;
    private TextInputEditText etMessage;
    private FloatingActionButton fabSend;
    private ChatAdapter chatAdapter;
    private List<ChatModel> chatList;
    private String videoId, videoTitle;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_chat);

        // Get video data from intent
        videoId = getIntent().getStringExtra("videoId");
        videoTitle = getIntent().getStringExtra("videoTitle");

        initViews();
        setupToolbar();
        setupRecyclerView();
        setupClickListeners();
        loadInitialMessages();
    }

    private void initViews() {
        toolbar = findViewById(R.id.toolbar);
        rvChatMessages = findViewById(R.id.rvChatMessages);
        etMessage = findViewById(R.id.etMessage);
        fabSend = findViewById(R.id.fabSend);
    }

    private void setupToolbar() {
        setSupportActionBar(toolbar);
        if (videoTitle != null) {
            toolbar.setTitle(videoTitle);
        }
        toolbar.setNavigationOnClickListener(v -> finish());
    }

    private void setupRecyclerView() {
        chatList = new ArrayList<>();
        chatAdapter = new ChatAdapter(chatList);

        LinearLayoutManager layoutManager = new LinearLayoutManager(this);
        layoutManager.setStackFromEnd(true); // Scroll to bottom
        rvChatMessages.setLayoutManager(layoutManager);
        rvChatMessages.setAdapter(chatAdapter);
    }

    private void setupClickListeners() {
        fabSend.setOnClickListener(v -> sendMessage());
        
        // Send on Enter key (optional)
        etMessage.setOnEditorActionListener((v, actionId, event) -> {
            sendMessage();
            return true;
        });
    }

    private void sendMessage() {
        String message = etMessage.getText().toString().trim();

        if (TextUtils.isEmpty(message)) {
            return;
        }

        // Add user message
        ChatModel userMessage = new ChatModel(message, ChatModel.TYPE_USER, 
                String.valueOf(System.currentTimeMillis()), videoId);
        chatAdapter.addMessage(userMessage);
        etMessage.setText("");
        
        // Scroll to bottom
        rvChatMessages.smoothScrollToPosition(chatList.size() - 1);

        // TODO: Send message to backend and get AI response
        // For now, simulate AI response
        simulateAiResponse(message);
    }

    private void simulateAiResponse(String userMessage) {
        // Simulate AI thinking delay
        rvChatMessages.postDelayed(() -> {
            String aiResponse = "This is a sample AI response to: \"" + userMessage + "\". " +
                    "In a real implementation, this would be generated by the backend AI service.";
            
            ChatModel aiMessage = new ChatModel(aiResponse, ChatModel.TYPE_AI,
                    String.valueOf(System.currentTimeMillis()), videoId);
            chatAdapter.addMessage(aiMessage);
            
            // Scroll to bottom
            rvChatMessages.smoothScrollToPosition(chatList.size() - 1);
        }, 1000);
    }

    private void loadInitialMessages() {
        // Add welcome message
        ChatModel welcomeMessage = new ChatModel(
                "Hello! I'm here to help you understand this video better. Ask me anything!",
                ChatModel.TYPE_AI,
                String.valueOf(System.currentTimeMillis()),
                videoId
        );
        chatAdapter.addMessage(welcomeMessage);
    }
}

